version: '3.8'
networks:
  cas-example1-net:
services:
  cas_example1_ui:
    build:
      context: /home/casservertest1/server_1/cas_example1_ui
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - cas-example1-net
  cas_example1:
    build:
      context: /home/casservertest1/server_1/cas_example1
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - cas-example1-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/cas?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
      - data.redis.host=redis
    depends_on:
      mysql_1:
        condition: service_healthy
      redis_1:
        condition: service_healthy
  mysql_1:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - cas-example1-net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
  redis_1:
    image: redis:latest
    restart: always
    container_name: redis_1
    ports:
      - "6379:6379"
    networks:
      - cas-example1-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 10s
